apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: bedpl26e8-nodejs 
  janus-idp.io/tekton: bedpl26e8-nodejs
  backstage.io/kubernetes-id: bedpl26e8-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bedpl26e8-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml